-- ⚠ SUPERSEDED — do not run this file.
--
-- This was a second, hand-maintained copy of the schema sitting beside
-- supabase/migrations/. Having two made drift inevitable, and by v1 this copy
-- was wrong in ways that would break a rebuilt database:
--
--   * no `stock_transactions.fee` column, which the app reads and writes
--   * `stock_transactions.quantity INTEGER`, while the app books fractional
--     shares into what is actually a numeric column
--   * phantom `offer_price` / `repurchase_price` on mutual_fund_transactions
--   * no user_profiles, feature_flags, admin_audit_log or deletion_log, and
--     none of the nine functions, triggers or the signup hook
--
-- The schema now lives in exactly one place:
--
--     supabase/migrations/20260927000000_baseline_live_schema.sql
--
-- That file is idempotent and reconciled against the live project — it can be
-- applied to the existing database or used to build one from empty.
--
-- Apply it with the Supabase CLI:
--
--     supabase link --project-ref YOUR_PROJECT_REF
--     supabase db push
--
-- or paste it into the SQL Editor in the Supabase dashboard.
--
-- This file is kept only so that a bookmark or an old runbook pointing at it
-- lands on this note rather than on a schema that no longer matches reality.
